# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_0.xci
# IP: The module: 'ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/FPGA7020/qmx/qmx/4_SourceCode/1_FPGA_Design/ZYNQ_7020_FPGA/18_hs_ad_da/hs_ad_da.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
